# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test
  pod 'SQLCipher'

  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'test-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test-tvOS

  target 'test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
